### ISSUE TITLE
Add sample screenshot to readme

### ISSUE THREAD

**Issue by mucsi96** [robhil/grunt-protractor-cucumber-html-report#18]
It would be very useful to add a sample screenshot to readme.md to provide an early feedback about the capabilities of this package.

**Comment by maciejkamela** [comment]
Hi, yes it makes sense. I have still one open pull request, so I will add some printscreens both for old layout and for new one.

**Comment by mucsi96** [comment]
Cool! I also don't understand what this package has related to Protractor. From the code it looks like this package could be used without Protractor. Only a generated cucumber JSON file is needed.

**Comment by maciejkamela** [comment]
yes, UR right, we use cucmber with protractor. and now there is no sense to rename this plugin

**Comment by maciejkamela** [comment]
hi,
Screenshots are now available in 0.2.6 version.
Best Regards
Camel

**Comment by mucsi96** [comment]
Thanks!
