### ISSUE TITLE
Support for multi capabilities

### ISSUE THREAD

**Issue by cuongluu-msm** [robhil/grunt-protractor-cucumber-html-report#5]
When you use multi capabilities it will create multiple JSON reports.  Is it possible to added support for this so you can give it a directory so it will create a HTML report for each of the JSON reports?

**Comment by camel99** [comment]
Hi there,
Thanks for your question. So far we haven't got the need to run tests on more than one browser, however today I was trying to configure our project to do so but I've encountered some problem. Could you please send me your multicapabilities and selenium.sh settings.
In multicapabilities I've got:

multicapabilities: [{
    'browserName': 'chrome',
    'browserName': 'firefox',
}] 
and in selenium I have:  java -jar selenium-server-standalone-2.45.jar -Dwebdriver.chrome.driver=chromedriver

**Comment by maciejkamela** [comment]
Hi there,
Thanks for your question. 
So far we haven't run tests on more than one browser, however today I was trying to configure our project to do so but I've encountered some problem. Could you please send me your multicapabilities and selenium.sh settings.
In multicapabilities I've got:
multicapabilities: [{
'browserName': 'chrome',
'browserName': 'firefox',
}] 
and in selenium I have:

java -jar selenium-server-standalone-2.45.jar -Dwebdriver.chrome.driver=chromedriver 
-Dwebdriver.firefox.driver=/user/bin/firefox
Not sure how webdriver for firefox should look like.

Thanks
